[project]
name = "ideal-group"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.0",
    "pyinstaller>=6.18.0",
    "pyside6>=6.8.0",
]
